### ISSUE TITLE
Inserting the plug-in shows a blank

### ISSUE THREAD

**Issue by LvShuaiChao** [terence-bonhomme/rnyt#24]
I set up according to your operation, but I found that nothing is displayed. What is displayed is that you have set up according to your operation, but I found that nothing is displayed. What is displayed is a blank, and the URL cannot be inserted at all. , Can you help me see what the situation is like? I have tried both the web version and the client, and they are all in the same situation

![image](https://user-images.githubusercontent.com/35528109/146338995-44c1177f-5a99-4536-929e-fe9cd6197913.png)
![image](https://user-images.githubusercontent.com/35528109/146339004-3c91e25d-60e0-4e6a-804f-220d4d7c9984.png)
![image](https://user-images.githubusercontent.com/35528109/146339007-0538c199-6427-4e34-8ceb-9c6b93de8d0e.png)
![image](https://user-images.githubusercontent.com/35528109/146339019-c892998e-9df7-4945-9bc2-1aed14fe79d7.png)
![image](https://user-images.githubusercontent.com/35528109/146339028-0ca06008-b728-4583-a96a-304293a9be9e.png)

**Comment by terence-bonhomme** [comment]
The plugin is working for me at the moment.

You can't use the plugin if you go to https://local-maroon-badger.glitch.me .

What is your "Plugin Information"?

<img width="666" alt="example-1" src="https://user-images.githubusercontent.com/95495533/146375501-34acfe60-78ad-42c9-a4f7-06ebdbc29b6d.png">
<img width="645" alt="example-2" src="https://user-images.githubusercontent.com/95495533/146375538-001327a7-a169-45ad-925d-60e59f087feb.png">

Can you read errors when you press F12 in your browser? What is your browser?

**Comment by LvShuaiChao** [comment]
![image](https://user-images.githubusercontent.com/35528109/146488499-a06d6ad6-1db6-401f-bb25-8f83a5ceaa50.png)

This is the information of my plug-in. My browser is Google browser.

**Comment by terence-bonhomme** [comment]
Chrome should be fine.

Have you got red errors when you press f12?

**Part 1**

Have you kept the rem "RemNote YT"? 
Have you moved it?
Have you modified something?

The rem should be like it and be placed on the top level.

- RemNote YT
  - dark_mode: 0
  - width: 65
  - playback_speed: 1
  - delay: 0
  - caption: 0

Can you add another plugin with the name "rnyt -np" then test it? It means "no parameter", it doesn't use settings. I want to know if the issue is from the settings.

**Part 2**

Here is the rem stucture :
- plugin
  - video link
  - timestamp 1
  - timestamp 2
  - ... 

It should be like it when you begin, the rem has no child :

- plugin

If the first child is not a YouTube's link, it is broken.

**Part 3**

You have 2 ways to use the plugin.

way 1:
1. plugin command with /
2. input the link 

way 2:
1. paste the YouTube's link in RemNote
2. go into the rem
3. plugin command with /

Can you try the second way?
